version: "3.9"


services:
  greeter:
    hostname: greeter.local
    build: .
    environment:
      RELEASE_DISTRIBUTION: name
      RELEASE_NODE: greeter@greeter.local
      RELEASE_COOKIE: secret

  livebook:
    hostname: livebook.local
    image: ghcr.io/livebook-dev/livebook:0.9.2
    volumes:
      - ./apps:/apps
    environment:
      LIVEBOOK_DEFAULT_RUNTIME: attached:greeter@greeter.local:secret
      LIVEBOOK_COOKIE: secret
      LIVEBOOK_NODE: livebook@livebook.local
      LIVEBOOK_DISTRIBUTION: name
      LIVEBOOK_PORT: 4100
      LIVEBOOK_IFRAME_PORT: 4101
      LIVEBOOK_TOKEN_ENABLED: "true"
      LIVEBOOK_APPS_PATH: /apps
      LIVEBOOK_APPS_PATH_PASSWORD: secretsecret
      LIVEBOOK_SECRET_KEY_BASE: 7ki4hExM22rWQ5wdnp00mlcmLg5en+uqJ90YKM45vVAVU4lA4Xl8jMCpGw4zlMfW
      LIVEBOOK_PASSWORD: secretsecret
    depends_on:
      - greeter
    ports:
      - 4100:4100
      - 4101:4101
